project:
  type: website
  output-dir: docs

website:
  title: "smartycope"
  navbar:
    right:
      - about.qmd
      - icon: smartycope
        href: https://avatars.githubusercontent.com/u/60020173?v=4
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
